const Product = require('../models/Product');

const products = [
  {
    name: 'MacBook Air M1',
    brand: 'Apple',
    category: 'Laptop',
    price: 62999,
    originalPrice: 92000,
    condition: 'Like New',
    ram: '8GB',
    storage: '256GB SSD',
    processor: 'Apple M1 8-Core',
    display: '13.3" Retina IPS',
    battery: '12 hours',
    warranty: '6 months',
    description: 'Apple M1 chip with incredible performance and battery life. Near-mint condition, fully tested and certified by Retech Revival engineers.',
    images: [],
    rating: 4.9,
    reviews: 124,
    tags: ['apple', 'macbook', 'm1', 'ultrabook']
  },
  {
    name: 'Dell XPS 13',
    brand: 'Dell',
    category: 'Laptop',
    price: 48500,
    originalPrice: 85000,
    condition: 'Excellent',
    ram: '16GB',
    storage: '512GB SSD',
    processor: 'Intel Core i7-11th Gen',
    display: '13.4" FHD+ InfinityEdge',
    battery: '8 hours',
    warranty: '6 months',
    description: 'Premium ultrabook with stunning display and powerful performance. Ideal for developers and designers.',
    images: [],
    rating: 4.7,
    reviews: 89,
    tags: ['dell', 'xps', 'ultrabook', 'developer']
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon',
    brand: 'Lenovo',
    category: 'Laptop',
    price: 42000,
    originalPrice: 78000,
    condition: 'Good',
    ram: '16GB',
    storage: '512GB SSD',
    processor: 'Intel Core i7-10th Gen',
    display: '14" FHD IPS Anti-Glare',
    battery: '7 hours',
    warranty: '3 months',
    description: 'Business-class durability meets lightweight design. Military-grade certified. Perfect for students and professionals.',
    images: [],
    rating: 4.6,
    reviews: 67,
    tags: ['lenovo', 'thinkpad', 'business', 'professional']
  },
  {
    name: 'HP Spectre x360',
    brand: 'HP',
    category: 'Laptop',
    price: 55000,
    originalPrice: 95000,
    condition: 'Like New',
    ram: '16GB',
    storage: '512GB SSD',
    processor: 'Intel Core i7-11th Gen',
    display: '13.5" OLED Touchscreen 360°',
    battery: '10 hours',
    warranty: '6 months',
    description: 'Convertible 2-in-1 with stunning OLED display. Use as laptop or tablet. Barely used, like new.',
    images: [],
    rating: 4.8,
    reviews: 45,
    tags: ['hp', 'spectre', '2-in-1', 'convertible', 'oled']
  },
  {
    name: 'ASUS ROG Zephyrus G14',
    brand: 'ASUS',
    category: 'Laptop',
    price: 68000,
    originalPrice: 112000,
    condition: 'Excellent',
    ram: '16GB',
    storage: '1TB SSD',
    processor: 'AMD Ryzen 9 5900HS',
    display: '14" QHD 120Hz',
    battery: '6 hours',
    warranty: '6 months',
    description: 'Powerful gaming laptop with AMD Ryzen 9 and NVIDIA RTX 3060. Excellent for gaming and content creation.',
    images: [],
    rating: 4.8,
    reviews: 212,
    tags: ['asus', 'rog', 'gaming', 'amd', 'rtx']
  },
  {
    name: 'MacBook Pro 13" M2',
    brand: 'Apple',
    category: 'Laptop',
    price: 79999,
    originalPrice: 129000,
    condition: 'Like New',
    ram: '8GB',
    storage: '256GB SSD',
    processor: 'Apple M2 8-Core',
    display: '13.3" Liquid Retina',
    battery: '18 hours',
    warranty: '6 months',
    description: 'The latest M2 chip in a compact form. Unmatched performance-per-watt. Perfect for creative professionals.',
    images: [],
    rating: 4.95,
    reviews: 56,
    tags: ['apple', 'macbook', 'm2', 'pro']
  },
  {
    name: 'Acer Swift 5',
    brand: 'Acer',
    category: 'Laptop',
    price: 31000,
    originalPrice: 58000,
    condition: 'Good',
    ram: '8GB',
    storage: '256GB SSD',
    processor: 'Intel Core i5-11th Gen',
    display: '14" FHD IPS',
    battery: '9 hours',
    warranty: '3 months',
    description: 'Ultra-lightweight at just 990g. Great battery life and everyday performance. Budget-friendly pick.',
    images: [],
    rating: 4.3,
    reviews: 34,
    tags: ['acer', 'swift', 'lightweight', 'budget']
  },
  {
    name: 'HP EliteBook 840 G8',
    brand: 'HP',
    category: 'Laptop',
    price: 44000,
    originalPrice: 75000,
    condition: 'Excellent',
    ram: '16GB',
    storage: '512GB SSD',
    processor: 'Intel Core i7-11th Gen',
    display: '14" FHD Sure View Privacy',
    battery: '8 hours',
    warranty: '6 months',
    description: 'Enterprise-grade business laptop with built-in privacy screen. Ideal for professionals handling sensitive data.',
    images: [],
    rating: 4.5,
    reviews: 28,
    tags: ['hp', 'elitebook', 'business', 'enterprise', 'privacy']
  },
  {
    name: 'Lenovo IdeaPad Gaming 3',
    brand: 'Lenovo',
    category: 'Laptop',
    price: 38000,
    originalPrice: 65000,
    condition: 'Good',
    ram: '8GB',
    storage: '512GB SSD',
    processor: 'AMD Ryzen 5 5600H',
    display: '15.6" FHD 120Hz',
    battery: '5 hours',
    warranty: '3 months',
    description: 'Entry-level gaming laptop with great performance for the price. Comes with NVIDIA GTX 1650.',
    images: [],
    rating: 4.2,
    reviews: 78,
    tags: ['lenovo', 'gaming', 'amd', 'gtx', 'budget']
  },
  {
    name: 'Microsoft Surface Pro 8',
    brand: 'Microsoft',
    category: 'Tablet/Laptop',
    price: 71000,
    originalPrice: 115000,
    condition: 'Like New',
    ram: '16GB',
    storage: '256GB SSD',
    processor: 'Intel Core i5-11th Gen',
    display: '13" PixelSense 2880x1920 120Hz',
    battery: '8 hours',
    warranty: '6 months',
    description: 'Premium 2-in-1 tablet with detachable keyboard. Exceptional pen input for note-taking and creative work.',
    images: [],
    rating: 4.7,
    reviews: 41,
    tags: ['microsoft', 'surface', '2-in-1', 'tablet', 'pen']
  }
];

async function seed() {
  try {
    await Product.deleteMany({});
    await Product.insertMany(products);
    console.log(`🌱 Seeded ${products.length} products to MongoDB`);
  } catch (err) {
    console.error('Seed error:', err.message);
  }
}

module.exports = seed;
